AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  micro-quiz-v2

  Sample SAM Template for micro-quiz-v2
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  QuizAnswersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: quiz-answers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: studentId
          AttributeType: S
        - AttributeName: questionId
          AttributeType: S
      KeySchema:
        - AttributeName: studentId
          KeyType: HASH
        - AttributeName: questionId
          KeyType: RANGE

  AnswerSubmissionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
    Properties:
      CodeUri: answer-submission/
      Handler: dist/answer-submission/app.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref QuizAnswersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QuizAnswersTable
      Events:
        AnswerSubmission:
          Type: Api
          Properties:
            Path: /answer-submission
            Method: post

  GradingSchedulerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
    Properties:
      CodeUri: grading-scheduler/
      Handler: dist/grading-scheduler/app.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref QuizAnswersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QuizAnswersTable
      Events:
        GradingSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

Outputs:
  AnswerSubmissionApi:
    Description: "API Gateway endpoint URL for Prod stage for Answer Submission function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/answer-submission/"
  AnswerSubmissionFunction:
    Description: "Answer Submission Lambda Function ARN"
    Value: !GetAtt AnswerSubmissionFunction.Arn
  AnswerSubmissionFunctionIamRole:
    Description: "Implicit IAM Role created for Answer Submission function"
    Value: !GetAtt AnswerSubmissionFunctionRole.Arn
  QuizAnswersTableName:
    Description: "DynamoDB table name"
    Value: !Ref QuizAnswersTable
